#ifndef FGPP_DEF_GL_VERSION_H
#define FGPP_DEF_GL_VERSION_H

namespace fg {
    enum GLVersion
    {
        GL_VERSION_INVALID = 0x0,

#define GL_VERSION_TYPE_POS 16
#define GL_VERSION_TYPE_BITS 16
#define GL_VERSION_TYPE ( 1 << GL_VERSION_TYPE_POS )

#define GL_VERSION_MAJOR_POS 8
#define GL_VERSION_MAJOR_BITS 8
#define GL_VERSION_MAJOR ( 1 << GL_VERSION_MAJOR_POS )

        GL_VERSION_TYPE_MASK = ( ( 1 << GL_VERSION_TYPE_BITS ) - 1 ) << GL_VERSION_TYPE_POS,
        GL_VERSION_MAJOR_MASK = ( ( 1 << GL_VERSION_MAJOR_BITS ) - 1 ) << GL_VERSION_MAJOR_POS,

        GL_VERSION_BASE = GL_VERSION_TYPE,
        GL_VERSION_1_0 = GL_VERSION_BASE + GL_VERSION_MAJOR,
        GL_VERSION_1_1,
        GL_VERSION_1_2,
        GL_VERSION_1_3,
        GL_VERSION_1_4,
        GL_VERSION_1_5,
        GL_VERSION_2_0 = GL_VERSION_1_0 + GL_VERSION_MAJOR,
        GL_VERSION_2_1,
        GL_VERSION_3_0 = GL_VERSION_2_0 + GL_VERSION_MAJOR,
        GL_VERSION_3_1,
        GL_VERSION_3_2,
        GL_VERSION_3_3,
        GL_VERSION_4_0 = GL_VERSION_3_0 + GL_VERSION_MAJOR,
        GL_VERSION_4_1,
        GL_VERSION_4_2,
        GL_VERSION_4_3,
        GL_VERSION_4_4,

        GLES_VERSION_BASE = GL_VERSION_BASE + GL_VERSION_TYPE,
        GLES_VERSION_1_0 = GLES_VERSION_BASE + GL_VERSION_MAJOR,
        GLES_VERSION_1_1,
        GLES_VERSION_2_0 = GLES_VERSION_1_0 + GL_VERSION_MAJOR,
        GLES_VERSION_3_0 = GLES_VERSION_2_0 + GL_VERSION_MAJOR,

#undef  GL_VERSION_MAJOR
#undef  GL_VERSION_MAJOR_BITS
#undef  GL_VERSION_MAJOR_POS

#undef  GL_VERSION_TYPE
#undef  GL_VERSION_TYPE_BITS
#undef  GL_VERSION_TYPE_POS
    };
}

#endif  // FGPP_DEF_GL_VERSION_H
